Documentation:
  Enabled: false

AllCops:
  RunRailsCops: false
  Include:
    - Gemfile
    - lib/tasks/*
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - db/**/*
    - bin/*

Style/ClassVars:
  Enabled: false
